# %load loadFundamentalTensor.py

import scipy.io as sio
import numpy as np

def main():
    print('Function Prototypes: ')
    
    print('X, numWeek, numDow, numHour, numItems, numOfCustomers = loadFundamentalTensor(filename)')
    print('Example Usage:')
    print('X,numWeek,numDow,numHour,numItems,numOfCustomers = loadFundamentalTensor(\'matfiles/AllHours_Item_Customer_Tensor.mat\')  ')
    
    print('\nInstructions')
    print('In order to view the code, type: %load loadFundamentalTensor.py')
    print('In order to modify the code, to the first line of the cell add: %%writefile loadFundamentalTensor.py')
    print('Note that after modifying the code, you should run the cell again: %run loadFundamentalTensor.py')

if __name__ == "__main__": main()

def clearIrrelevantKeys(dictionary):
    '''This function gets rid of irrelevant dictionary keys generated by scipy.io'''
    
    if '__globals__' in dictionary:
        del dictionary['__globals__']
    if '__header__' in dictionary:
        del dictionary['__header__']
    if '__version__' in dictionary:
        del dictionary['__version__']
    
    return dictionary

def loadFundamentalTensor(filename, numHour):
    '''
    Load the tensor from a mat file
    In the mat file, the tensor is stored as a dictionary. 
    Each dictionary key corresponds to a customer. 
    Value corrseponding to each key is a scipy.sparse matrix, not a tensor. 
    In this function, we convert the dictionary to a tensor with dimensions 
    (numWeek x numDow x numHour x numItem x numCustomer). Note that this tensor is not sparse.
    '''
    
    tempX = sio.loadmat(filename)

    tempX = clearIrrelevantKeys(tempX)
    
    numOfCustomers = len(tempX)
    numAllHours, numItems = tempX['0'].shape
    
    X = np.zeros((numAllHours,numItems,numOfCustomers))
    
    for idx in range(numOfCustomers):
        X[:,:,idx] = tempX[str(idx)].todense()
    
    numDow = 7
    
    # Find the number of days and the number of weeks the transactions are done
    numDay = numAllHours//numHour
    numWeek = numDay//numDow
    
    newX = np.reshape(X[0:numWeek*numDow*numHour,:,:],(numWeek,numDow,numHour,numItems,numOfCustomers))
    
    return newX, numWeek, numDow, numHour, numItems, numOfCustomers


def loadFundamentalTensorCustomer(filename, customerIndex, numHour):
    tempX = sio.loadmat(filename)

    tempX = clearIrrelevantKeys(tempX)
    
    numOfCustomers = len(tempX)
    numAllHours, numItems = tempX['0'].shape
    
    X = np.zeros((numAllHours,numItems,1))
    
    X[:,:,0] = tempX[str(customerIndex)].todense()
    
    numDow = 7
    
    # Find the number of days and the number of weeks the transactions are done
    numDay = numAllHours//numHour
    numWeek = numDay//numDow
    
    newX = np.reshape(X[0:numWeek*numDow*numHour,:,:],(numWeek,numDow,numHour,numItems,1))
    
    return newX


def loadViewCustomer(filename, customerIndex):
    tempX = sio.loadmat(filename)
    custView = tempX['data'][:,:,:,:,customerIndex,None]
    
    return custView