
# Including the required libraries .
import tornado.ioloop
import tornado.web
from tornado.httpserver import HTTPServer
from tornado.escape import json_encode

import os
import json
import requests
import numpy as np
import scipy.io as sio

import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt



# Setting host name, port number, directory name and the static path. 
HOST = 'localhost'
PORT = 8880

DIRNAME = os.path.dirname(os.path.realpath('__file__'))
STATIC_PATH = os.path.join(DIRNAME, '.')


# Creating global variables. 
global selectedCustomerIndex2Id
selectedCustomerIndex2Id = np.loadtxt('files/customersIndex2Id.txt', dtype='int')

# In later implementation, X will represent the sales tensor of all customers.
# For now, it is randomly generated. 
#global X
#X = np.random.rand(10,20,30)


#############

def clearIrrelevantKeys(dictionary):
    '''This function gets rid of irrelevant dictionary keys generated by scipy.io'''
    
    if '__globals__' in dictionary:
        del dictionary['__globals__']
    if '__header__' in dictionary:
        del dictionary['__header__']
    if '__version__' in dictionary:
        del dictionary['__version__']
    
    return dictionary


def loadFundamentalTensorCustomer(filename, customerIndex):
    tempX = sio.loadmat(filename)

    tempX = clearIrrelevantKeys(tempX)
    
    numOfCustomers = len(tempX)
    numAllHours, numItems = tempX['0'].shape
    
    X = np.zeros((numAllHours,numItems,1))
    
    X[:,:,0] = tempX[str(customerIndex)].todense()
    
    numDow = 7
    numHour = 16
    
    # Find the number of days and the number of weeks the transactions are done
    numDay = numAllHours//numHour
    numWeek = numDay//numDow
    
    newX = np.reshape(X[0:numWeek*numDow*numHour,:,:],(numWeek,numDow,numHour,numItems,1))
    
    return newX


def collapseTensor(tensor, dimensions, function):
    '''
    Given the tensor, dimensions to be collapsed over and the function applied during collapsing,
    this function generates new tensor and keeps the dimensions.
    
    Inputs: tensor
            dimensions: an array in the form of an binary array
            function: a string whose value must be one of the following: 'sum', 'binary' or 'count'
                      'sum' sums the tensor over the given dimensions.
                      'binary' generates a tensor with values 0 or 1.
                      'count' sums up the number of occurences in the tensor.
                      
    Example: newTensor = collapseTensor(tensor, [1,0,1,0], 'sum')
             shape of tensor:    (2 x 3 x 4 x 5) 
             shape of newTensor: (1 x 3 x 1 x 5)
    '''
    
    dimensions = np.array(dimensions)
    
    if dimensions.shape[0] > len(tensor.shape):
        print('Invalid Parameter: Dimensions exceed the tensor size')
        return tensor
    
    indices = np.where(dimensions>0)[0]  
    
    for i in range(len(indices)):
        ax = indices[i]       
        
        if function is 'binary':
            tensor = np.sum(tensor, axis=ax, keepdims=True)
            tensor[np.where(tensor>0)]=1
        elif function is 'count':
            tensor[np.where(tensor>0)]=1
            tensor = np.sum(tensor, axis=ax, keepdims=True)
        else: # 'sum'
            tensor = np.sum(tensor, axis=ax, keepdims=True)

    return tensor



############

# Code segment that will bu used in the landing page. Gives examples of how-to-use the functionalities. 
class MainPage(tornado.web.RequestHandler):
    def get(self):
        self.post()
        
    def post(self):
        self.write('<html><head><h1> Obase Tornado Server </h1></head><br>'
                   '<body><h2> Example Usages </h2><br>'
                   '<b> 45.55.237.86:8880/customerInfo/110236 </b> <br>'
                   'Displays demographic information of customer with id = 110236 <br>'
                   'Some customer ids to use for customerInfo: 110236, 100240 <br><br>'
                   '<b> 45.55.237.86:8880/customerSale/99888001 </b> <br>'
                   'Displays heatmap of the sales of customer with id = 99888001 <br>'
                   'Some customer ids to use for customerSale: 99888001, 991921217, 99958429 <br><br>'
                   '<b> 45.55.237.86:8880/customerSaleJson/99888001 </b> <br>'
                   'Displays the image url the sales matrix of customer with id = 99888001 in JSON format <br>'
                   'Some customer ids to use for customerSaleJson: 99888001, 991921217, 99958429 <br><br>'
                   '</body></html>')
        
        

# Code segment that will return customer demographic information as a JSON object. 
# The customer id is given. 
# From the api provided, the code segment executes query to get information and convert it to JSON format.
class CustomerInfo(tornado.web.RequestHandler):
    def get(self, parameter):
        self.post(parameter)
    
    def post(self, parameter):
        customerId = int(parameter)
        #self.write("Customer Id: %d " % customerId)
        
        r = requests.get('http://212.57.2.68:93/api/database/musteri?$filter=IdMusteri+eq+%d'%customerId)

        info = json.dumps(r.json())

        #self.write("Customer Demographic Information: %s" % info)
        self.write("%s" % info)
   

# Given the customer id, this code segment get the sales matrix of the customer, saves it in .png format and displays the image. 
class CustomerSale(tornado.web.RequestHandler):
    def get(self, parameter):
        self.post(parameter)
    
    def post(self, parameter):
        customerId = int(parameter)
        customerIndex = np.where(selectedCustomerIndex2Id==customerId)[0][0]
        
        X = loadFundamentalTensorCustomer('files/AllHours_Item_Customer_Tensor.mat', customerIndex)
        X = collapseTensor(X, [1,0,0,1,0], 'sum')
        SalesTensor = X[0,:,:,0,0] 
        
        plt.figure
        plt.imshow(SalesTensor, aspect='auto', interpolation='nearest',vmin=0, vmax=100)
        plt.savefig('./files/%d.png' % customerId)
        

        self.write('<html>'
                   'Sale Matrix of Customer %d <br>'
                   '<img src=\"/files/%d.png\"><br></body></html>' % (customerId,customerId))
        
        imageUrl = ("45.55.237.86:%s/files/%d.png" % (PORT,customerId))
        
        info = json.dumps({"IdMusteri": customerId, "image_url": imageUrl})
        self.write("%s" % info)
        
# Given the customer id, this code segment get the sales matrix of the customer, saves it in .png format and displays the json. 
class CustomerSaleJson(tornado.web.RequestHandler):
    def get(self, parameter):
        self.post(parameter)
    
    def post(self, parameter):
        customerId = int(parameter)
        customerIndex = np.where(selectedCustomerIndex2Id==customerId)[0][0]
        
        X = loadFundamentalTensorCustomer('files/AllHours_Item_Customer_Tensor.mat', customerIndex)
        X = collapseTensor(X, [1,0,0,1,0], 'sum')
        SalesTensor = X[0,:,:,0,0] 
        
        plt.figure
        plt.imshow(SalesTensor, aspect='auto', interpolation='nearest',vmin=0, vmax=100)
        plt.savefig('./files/%d.png' % customerId)

        imageUrl = ("45.55.237.86:%s/files/%d.png" % (PORT,customerId))
        
        info = json.dumps({"IdMusteri": customerId, "image_url": imageUrl})
        self.write("%s" % info)
        
            
# The configuration of routes.
routes_config = [
    (r"/", MainPage), 
    (r"/customerInfo/([^/]+)", CustomerInfo),
    (r"/customerSale/([^/]+)", CustomerSale),
    (r"/customerSaleJson/([^/]+)", CustomerSaleJson),
    (r"/(.*\.png)", tornado.web.StaticFileHandler,{"path": "." }),
]
application = tornado.web.Application(routes_config)


def start():
    print("Obase Tornado Server.\nStarting on host %s, port %s" % (HOST,PORT))
    http_server = HTTPServer(application, xheaders=True)
    http_server.listen(PORT)
    tornado.ioloop.IOLoop.instance().start()
    return application


if __name__ == "__main__":
    start()